
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef ACTUATOR_NODE_H
#define ACTUATOR_NODE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value);
const subindex * ObjDict_scanIndexOD (UNS16 wIndex, UNS8 *size, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data ObjDict_Data;
extern UNS16 Actuator;		/* Mapped at index 0x2001, subindex 0x00*/

#endif // ACTUATOR_NODE_H
